components:
- type: ColumnPanel
  properties: {role: null, tooltip: '', border: '', foreground: '', visible: true,
    wrap_on: mobile, col_spacing: medium, spacing_above: small, col_widths: '{"ZTPEUH":2,"MUSPMU":58}',
    spacing_below: small, background: ''}
  name: column_panel_1
  layout_properties: {grid_position: 'WJFFQO,GAUXSE'}
  components:
  - type: Spacer
    properties: {height: 32}
    name: spacer_1
    layout_properties: {grid_position: 'JFBEHH,ZTPEUH'}
  - type: Label
    properties: {role: header-text, align: left, tooltip: '', border: '', foreground: '',
      visible: true, text: Ticket Details, font_size: null, font: '', spacing_above: small,
      icon_align: left, spacing_below: small, italic: false, background: '', bold: false,
      underline: false, icon: ''}
    name: label_1
    layout_properties: {grid_position: 'JFBEHH,MUSPMU'}
- type: Label
  properties: {role: null, align: left, tooltip: '', border: '', foreground: '', visible: true,
    text: 'Title:', font_size: null, font: '', spacing_above: small, icon_align: left,
    spacing_below: small, italic: false, background: '', bold: false, underline: false,
    icon: ''}
  name: label_4
  layout_properties: {grid_position: 'ZVTNVF,OHTGQB'}
- type: TextBox
  properties: {role: textbox-input, align: left, hide_text: false, tooltip: '', placeholder: '',
    border: '', enabled: true, foreground: '', visible: true, text: '', font_size: null,
    font: '', spacing_above: small, type: text, spacing_below: small, italic: false,
    background: '', bold: false, underline: false}
  name: title_box
  layout_properties: {grid_position: 'ZVTNVF,ZFBLHJ'}
  data_bindings:
  - {property: text, code: 'self.ticket_copy[''title'']', writeback: true}
- type: Label
  properties: {role: null, align: left, tooltip: '', border: '', foreground: '', visible: true,
    text: 'Category:', font_size: null, font: '', spacing_above: medium, icon_align: left,
    spacing_below: small, italic: false, background: '', bold: false, underline: false,
    icon: ''}
  name: label_2_copy
  layout_properties:
    col_widths: {}
    grid_position: OSNJJA,CPYPSZ
- type: DropDown
  properties:
    role: dropdown-border
    align: full
    tooltip: ''
    placeholder: select a category
    border: ''
    enabled: true
    foreground: ''
    items: ['']
    visible: true
    font_size: null
    font: ''
    spacing_above: small
    spacing_below: small
    italic: false
    background: ''
    bold: false
    underline: false
    include_placeholder: false
  name: category_dropdown
  layout_properties: {grid_position: 'OSNJJA,GBUXLP'}
  event_bindings: {change: filter_tickets}
  data_bindings:
  - {property: selected_value, code: 'self.ticket_copy[''category'']', writeback: true}
  - {property: items, code: 'list(set([x[''category''] for x in self.all_tickets]))'}
- type: Label
  properties: {role: null, align: left, tooltip: '', border: '', foreground: '', visible: true,
    text: 'Status:', font_size: null, font: '', spacing_above: medium, icon_align: left,
    spacing_below: small, italic: false, background: '', bold: false, underline: false,
    icon: ''}
  name: label_2
  layout_properties: {grid_position: 'AEDFFQ,LSRQZB'}
- type: DropDown
  properties:
    role: dropdown-border
    align: full
    tooltip: ''
    placeholder: select a status
    border: ''
    enabled: true
    foreground: ''
    items: ['', '']
    visible: true
    font_size: null
    font: ''
    spacing_above: small
    spacing_below: small
    italic: false
    background: ''
    bold: false
    underline: false
    include_placeholder: false
  name: status_dropdown
  layout_properties: {grid_position: 'AEDFFQ,JFHZOB'}
  data_bindings:
  - {property: selected_value, code: 'self.ticket_copy[''status'']', writeback: true}
  - {property: items, code: 'list(set([x[''status''] for x in self.all_tickets]))'}
  event_bindings: {change: filter_tickets}
- type: Label
  properties: {role: null, align: left, tooltip: '', border: '', foreground: '', visible: true,
    text: 'Priority:', font_size: null, font: '', spacing_above: medium, icon_align: left,
    spacing_below: small, italic: false, background: '', bold: false, underline: false,
    icon: ''}
  name: label_2_copy_2
  layout_properties:
    col_widths: {}
    grid_position: OHPOES,MQCXCH
- type: DropDown
  properties:
    role: dropdown-border
    align: full
    tooltip: ''
    placeholder: select a priority
    border: ''
    enabled: true
    foreground: ''
    items: ['']
    visible: true
    font_size: null
    font: ''
    spacing_above: small
    spacing_below: small
    italic: false
    background: ''
    bold: false
    underline: false
    include_placeholder: false
  name: priority_dropdown
  layout_properties: {grid_position: 'OHPOES,SUMKER'}
  data_bindings:
  - {property: selected_value, code: 'self.ticket_copy[''priority'']', writeback: true}
  - {property: items, code: 'list(set([x[''priority''] for x in self.all_tickets]))'}
  event_bindings: {change: filter_tickets}
- type: Label
  properties: {role: null, align: left, tooltip: '', border: '', foreground: '', visible: true,
    text: 'Agent:', font_size: null, font: '', spacing_above: medium, icon_align: left,
    spacing_below: small, italic: false, background: '', bold: false, underline: false,
    icon: ''}
  name: label_2_copy_4
  layout_properties:
    col_widths: {}
    grid_position: GDFSYH,HINAVG
- type: DropDown
  properties:
    role: dropdown-border
    align: full
    tooltip: ''
    placeholder: select an agent
    border: ''
    enabled: true
    foreground: ''
    items: ['', '']
    visible: true
    font_size: null
    font: ''
    spacing_above: small
    spacing_below: small
    italic: false
    background: ''
    bold: false
    underline: false
    include_placeholder: false
  name: agent_dropdown
  layout_properties: {grid_position: 'GDFSYH,KFKMPR'}
  data_bindings:
  - {property: selected_value, code: 'self.ticket_copy[''agent'']', writeback: true}
  - {property: items, code: 'list(set([(x[''agent''][''email''],x[''agent'']) for
      x in self.all_tickets]))'}
  event_bindings: {change: filter_tickets}
- type: Label
  properties: {role: null, align: left, tooltip: '', border: '', foreground: '', visible: true,
    text: 'Due:', font_size: null, font: '', spacing_above: small, icon_align: left,
    spacing_below: small, italic: false, background: '', bold: false, underline: false,
    icon: ''}
  name: label_3
  layout_properties: {grid_position: 'KNTJAR,BALZQQ'}
- type: DatePicker
  properties: {role: dropdown-border, align: left, max_date: '', pick_time: false,
    tooltip: '', placeholder: '', border: '', enabled: true, foreground: '', visible: true,
    font_size: null, font: '', spacing_above: small, spacing_below: small, italic: false,
    date: '', min_date: '', background: '', bold: false, underline: false, format: '%d/%m/%Y'}
  name: date_picker_1
  layout_properties: {grid_position: 'KNTJAR,HJQMEP'}
  data_bindings:
  - {property: date, code: 'self.ticket_copy[''due'']', writeback: true}
- type: Link
  properties: {role: null, url: '', align: left, tooltip: '', border: '', foreground: 'theme:Gray
      800', visible: true, text: Cancel, font_size: null, wrap_on: mobile, font: '',
    col_spacing: medium, spacing_above: small, icon_align: left, col_widths: '', spacing_below: small,
    italic: false, background: '', bold: false, underline: false, icon: ''}
  name: cancel_link
  layout_properties:
    col_widths: {}
    grid_position: KBYUOM,MECGNQ
  event_bindings: {click: cancel_link_click}
- type: Link
  properties: {role: null, url: '', align: right, tooltip: '', border: '', foreground: 'theme:Primary
      700', visible: true, text: Save, font_size: null, wrap_on: mobile, font: '',
    col_spacing: medium, spacing_above: small, icon_align: left, col_widths: '', spacing_below: small,
    italic: false, background: '', bold: false, underline: false, icon: ''}
  name: save_link
  layout_properties:
    col_widths: {}
    grid_position: KBYUOM,QROKFF
  event_bindings: {click: save_link_click}
container:
  type: ColumnPanel
  properties: {role: filter-form-shadow, tooltip: '', border: '', foreground: '',
    visible: true, wrap_on: mobile, col_spacing: medium, spacing_above: none, col_widths: '{"GBUXLP":32,"LSRQZB":15,"JFHZOB":45,"CPYPSZ":10,"MQCXCH":15,"SUMKER":45,"HINAVG":15,"KFKMPR":45,"BALZQQ":15,"HJQMEP":45,"OHTGQB":15,"ZFBLHJ":45}',
    spacing_below: none, background: ''}
  event_bindings: {show: form_show, refreshing_data_bindings: form_refreshing_data_bindings}
