roles:
- name: active
  components: [Link]
- {name: dash-up}
- {name: dash-down}
- name: no-margin
  components: [ColumnPanel]
- {name: tickets-form}
- {name: grey-bottom-border}
- {name: tickets-repeating-panel}
- {name: avatar}
- {name: ticket-filters-form}
- {name: grey-link}
- {name: scrollable}
- {name: dashboard-form}
- name: dropdown-border
  components: [DropDown, DatePicker]
- {name: full-height}
- {name: details-repeating-panel}
- {name: customer-details-form}
- {name: primary-button}
- {name: card-no-border}
- {name: card-with-border}
- {name: background-image}
- {name: background-colour}
