roles:
- name: active
  components: [Link]
- {name: dash-up}
- {name: dash-down}
- name: no-margin
  components: [ColumnPanel]
- {name: tickets-form}
- {name: grey-bottom-border}
- {name: tickets-repeating-panel}
- {name: avatar}
- {name: ticket-filters-form}
