roles:
- name: active
  components: [Link]
- {name: dash-up}
- {name: dash-down}
- name: no-margin
  components: [ColumnPanel]
- name: tickets-data-grid
  components: [DataGrid]
- {name: tickets-form}
- {name: grey-bottom-border}
